repos:
  - repo: https://github.com/godaddy/tartufo
    rev: v5.0.0
    hooks:
      - id: tartufo
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3.12
  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.0
    hooks:
      - id: flake8
  - repo: https://github.com/kxue43/post-merge-hooks
    rev: 0.2.0
    hooks:
      - id: remind-poetry-install
        stages: [post-merge, manual]
        always_run: true
        verbose: true
